// Stripe is supported in the following countries:

export const stripeCountriesList = [
  'Australia',
  'Austria',
  'Belgium',
  'Canada',
  'Denmark',
  'Finland',
  'France',
  'Germany',
  'Hong Kong',
  'Ireland',
  'Japan',
  'Luxembourg',
  'Netherlands',
  'New Zealand',
  'Norway',
  'Singapore',
  'Spain',
  'Sweden',
  'Switzerland',
  'United Kingdom',
  'United States',
  'Italy',
  'Portugal',
];
