# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, ‘10.0’

target 'SharetribeFlexMobileClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Your ‘node_modules’ directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod ‘React’, :path => ‘../node_modules/react-native’, :subspecs => [
    ‘Core’,
    ‘CxxBridge’, # Include this for RN >= 0.47
    ‘DevSupport’, # Include this to enable In-App Devmenu if RN >= 0.43
    ‘RCTText’,
    ‘RCTNetwork’,
    ‘RCTWebSocket’, # Needed for debugging
    ‘RCTAnimation’, # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
    ‘RCTImage’
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod ‘yoga’, :path => ‘../node_modules/react-native/ReactCommon/yoga’


  # Third party deps podspec link
  # Pods for SharetribeFlexMobileClient
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod ‘RNReanimated’, :path => ‘../node_modules/react-native-reanimated’
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNLanguages', :path => '../node_modules/react-native-languages'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod ‘DoubleConversion’, :podspec => ‘../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec’
  pod ‘glog’, :podspec => ‘../node_modules/react-native/third-party-podspecs/glog.podspec’

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end

    if target.name == "React"
      target.remove_from_project
    end
  end
end